Add miniconda python setup (esp. on Windows)

diff --git a/dot_bashrc b/dot_bashrc
--- a/dot_bashrc
+++ b/dot_bashrc
@@ -342,6 +342,23 @@ setpath_fzf() {
     [[ -n $ZSH_VERSION ]] && [[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh
 }
 
+# Sets PATH and adds some shell functions, e.g. `conda` itself.
+# Note: on Windows, miniconda shell hook fails with zsh due to
+# newline issues; see https://github.com/conda/conda/issues/13391
+# so this patches the setup file before sourcing it.
+setup_miniconda() {
+    if [[ -z $CONDA_EXE && -d $HOME/miniconda3/Scripts ]]; then
+        $HOME/miniconda3/Scripts/conda shell.zsh hook > $TMP/conda.sh
+        (cd $TMP; patch -s -p1 $TMP/conda.sh $HOME/.config/conda.patch)
+        source $TMP/conda.sh
+        # rm $TMP/conda.sh
+    fi
+    # miniconda doesn't provide `python3` but `python` is v3.
+    if ! has_command python3; then
+        alias python3='python'
+    fi
+}
+
 maybe_setpath() {
     # set up path.  Only do this once, to avoid duplicates.
     [[ -n $SETPATH_VERBOSE ]]  && echo "PATH: maybe_setpath"
@@ -371,6 +388,7 @@ maybe_setpath() {
         setpath_pyenv
         setpath_gcloud
         setpath_fzf
+        setup_miniconda
         setpath_all           # always run this at end for paths to always add
     fi
 }
